runtime: nodejs14
manual_scaling:
  instances: 1
network:
  session_affinity: true
env_variables:
  DB_HOST: 34.87.23.103
  DB_PORT: 3306
  DB_USER: tqnghia1998
  DB_PASS: tqnghi@
  DB_NAME: intranet
  INSTANCE_CONNECTION_NAME: quixotic-skill-311806:asia-southeast1:intranet-schema
beta_settings:
  cloud_sql_instances: quixotic-skill-311806:asia-southeast1:intranet-schema
